### ISSUE TITLE
Uncaught node.js Error

### ISSUE THREAD

**Issue by Syenta** [NewSpaces/gravit#193]
1. Gravit version - latest Beta
2. Place three objects on canvas
3. Select all objects
4. Enter 1 into Horizontal Spacing
5. Gravit crashes - Unable to close down via close, close all, red X - Ctrl + Alt + Del is the only way.

**Comment by anderswelt** [comment]
@anna-ignatenkova please check if you can reproduce and if yes fix it

**Comment by anna-ignatenkova** [comment]
Fixed.
However, here is another issue: when 'distribute' button is pressed several times, objects move slowly from their positions. I'm going to fix it too.

**Comment by anna-ignatenkova** [comment]
The same problem with objects movement was on repeated 'align' actions. Fixed.
