### ISSUE TITLE
BUG: drop shadow added to scanned hand sketch

### ISSUE THREAD

**Issue by cekuhnen** [NewSpaces/gravit#263]
![screen shot 2015-03-06 at 2 55 06 pm](https://cloud.githubusercontent.com/assets/11001547/6535167/cba34ebe-c410-11e4-9bfd-b95927b91429.png)

**Comment by anderswelt** [comment]
Can you tell me which zoom level you've used and whether you've enabled pixel preview mode or not?

**Comment by cekuhnen** [comment]
Zoom level does not matter. I did not have Pixel preview on.

But it seems all works now. I just gave it a new test.
![screen shot 2015-03-11 at 6 07 27 am](https://cloud.githubusercontent.com/assets/11001547/6596818/0077dfa4-c7b5-11e4-8633-2d37da65420e.png)

**Comment by newspaces-alex** [comment]
Closing this now if it occurs again in the new version please re-open :)
